name: Create packages

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  electron:
    strategy:
      matrix:
        image: [windows-latest]
    runs-on: ${{ matrix.image }}

    env:
      CSC_IDENTITY_AUTO_DISCOVERY: true
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # --- Windows Azure OIDC Login and Sign ---
      - name: Log in to Azure (Windows Only)
        if: matrix.os == 'windows-latest'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false
          
      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext -ErrorAction

      # - uses: actions/checkout@v4
      # - name: Use Node.js LTS
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*
      #     cache: 'npm'
      # - name: Install dependencies (Node.js)
      #   run: npm ci
      # - name: Build electron app
      #   run: npm run build:electron

      # - name: build package
      #   if: matrix.os == 'windows-latest'
      #   env:
      #     # Prevent electron-builder from auto-signing Windows
      #     CSC_IDENTITY_AUTO_DISCOVERY: false
      #     # DO NOT add WIN_CSC_* or Azure signing env vars here
      #   run: npx electron-builder build --x64 --arm64 --publish always

      # - name: Upload built packages
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifact-${{ matrix.image }}
      #     path: release/



  # plugin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js LTS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*
  #         cache: 'npm'
  #     - name: Authenticate with npm registry
  #       run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  #       env:
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     - name: Install dependencies (Node.js)
  #       run: npm ci
  #     - name: generate contents
  #       run: npm run build:plugin
  #     - name: publish
  #       run: npm publish
  #       working-directory: plugins
